# Generated by Django 4.1.2 on 2023-01-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('view_not_moderated_review', 'Видеть немодерированные отзывы')]},
        ),
    ]
